parameters:
    oro_requirejs.twig.class:             Oro\Bundle\RequireJSBundle\Twig\OroRequireJSExtension

services:
    oro_requirejs.twig.requirejs_extension:
        class:                            %oro_requirejs.twig.class%
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }
